secret:
  path: E:/eclipse/hono/hono-0.8/demo-certs/certs
hono:
  app:
    maxInstances: 1
    healthCheckPort: 8088
    healthCheckBindAddress: 0.0.0.0
  http:
    bindAddress: 0.0.0.0
    insecurePortBindAddress: 0.0.0.0
    insecurePortEnabled: true
    keyPath: ${secret.path}/http-adapter-key.pem
    certPath: ${secret.path}/http-adapter-cert.pem
  messaging:
    name: 'Hono HTTP Adapter'
    amqpHostname: hono-internal
    host: hono-dispatch-router.hono
    port: 5673
    keyPath: ${secret.path}/http-adapter-key.pem
    certPath: ${secret.path}/http-adapter-cert.pem
    trustStorePath: ${secret.path}/trusted-certs.pem
  registration:
    name: 'Hono HTTP Adapter'
    host: ${hono.registration.host}
    port: 5671
    credentialsPath: ${secret.path}/http-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  credentials:
    name: 'Hono HTTP Adapter'
    host: ${hono.registration.host}
    port: 5671
    credentialsPath: ${secret.path}/http-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  tenant:
    name: 'Hono HTTP Adapter'
    host: ${hono.registration.host}
    port: 5671
    credentialsPath: ${secret.path}/http-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  command:
    name: 'Hono HTTP Adapter'
    amqpHostname: hono-http-internal
    host: hono-dispatch-router.hono
    port: 5673
    keyPath: ${secret.path}/http-adapter-key.pem
    certPath: ${secret.path}/http-adapter-cert.pem
    trustStorePath: ${secret.path}/trusted-certs.pem
  metrics:
    legacy: true

# disable spring boot actuator endpoints
endpoints:
  enabled: false

management:
  metrics:
    export:
      graphite:
        host: influxdb.hono
        port: 2003
