secret:
  path: E:/eclipse/hono/hono-0.8/demo-certs/certs
hono:
  app:
    maxInstances: 1
    healthCheckPort: 8088
    healthCheckBindAddress: 0.0.0.0
  amqp:
    bindAddress: 0.0.0.0
    insecurePortBindAddress: 0.0.0.0
    insecurePortEnabled: true
    keyPath: ${secret.path}/amqp-adapter-key.pem
    certPath: ${secret.path}/amqp-adapter-cert.pem
  messaging:
    name: 'Hono AMQP Adapter'
    amqpHostname: hono-internal
    host: hono-dispatch-router.hono
    port: 5673
    keyPath: ${secret.path}/amqp-adapter-key.pem
    certPath: ${secret.path}/amqp-adapter-cert.pem
    trustStorePath: ${secret.path}/trusted-certs.pem
  registration:
    name: 'Hono AMQP Adapter'
    host: ${hono.registration.host}
    port: 5671
    credentialsPath: ${secret.path}/amqp-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  credentials:
    name: 'Hono AMQP Adapter'
    host: ${hono.registration.host}
    port: 5671
    credentialsPath: ${secret.path}/amqp-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  tenant:
    name: 'Hono AMQP Adapter'
    host: ${hono.registration.host}
    port: 5671
    credentialsPath: ${secret.path}/amqp-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  command:
    name: 'Hono AMQP Adapter'
    amqpHostname: hono-amqp-internal
    host: hono-dispatch-router.hono
    port: 5673
    keyPath: ${secret.path}/amqp-adapter-key.pem
    certPath: ${secret.path}/amqp-adapter-cert.pem
    trustStorePath: ${secret.path}/trusted-certs.pem
  metrics:
    legacy: true

# disable spring boot actuator endpoints
endpoints:
  enabled: false

management:
  metrics:
    export:
      graphite:
        host: influxdb.hono
        port: 2003
