hono:
  app:
    maxInstances: 1
  auth:
    amqp:
      bindAddress: 0.0.0.0
      keyPath: /run/secrets/auth-server-key.pem
      certPath: /run/secrets/auth-server-cert.pem
      trustStorePath: /run/secrets/trusted-certs.pem
    svc:
      permissionsPath: file:///run/secrets/sandbox-permissions.json
  metrics:
    legacy: true

# disable spring boot actuator endpoints, enable metrics
endpoints:
  enabled: false
management:
  metrics:
    export:
      graphite:
        host: influxdb.hono
        port: 2003
