secret:
  path: E:/eclipse/hono/hono-0.8/demo-certs/certs
hono:
  app:
    maxInstances: 1
    healthCheckBindAddress: 0.0.0.0
    healthCheckPort: 8088
  auth:
    host: ${hono.auth.host}
    port: 5671
    keyPath: ${secret.path}/device-registry-key.pem
    certPath: ${secret.path}/device-registry-cert.pem
    trustStorePath: ${secret.path}/trusted-certs.pem
    name: 'Hono Device Registry'
    validation:
      certPath: ${secret.path}/auth-server-cert.pem
  registry:
    amqp:
      bindAddress: 0.0.0.0
      keyPath: ${secret.path}/device-registry-key.pem
      certPath: ${secret.path}/device-registry-cert.pem
    rest:
      bindAddress: 0.0.0.0
      keyPath: ${secret.path}/device-registry-key.pem
      certPath: ${secret.path}/device-registry-cert.pem
      insecurePortBindAddress: 0.0.0.0
      insecurePortEnabled: true
    svc:
      filename: ${secret.path}/device-identities.json
#      filename: /var/lib/hono/device-registry/device-identities.json
      saveToFile: true
      signing:
        sharedSecret: ${hono.regAssertion.sharedSecret}
  credentials:
    svc:
      filename: ${secret.path}/credentials.json
#      filename: /var/lib/hono/device-registry/credentials.json
      saveToFile: true
  tenant:
    svc:
      filename: ${secret.path}/tenants.json
#      filename: /var/lib/hono/device-registry/tenants.json
      saveToFile: true
  metrics:
    legacy: true

management:
  metrics:
    export:
      graphite:
        host: influxdb.hono
        port: 2003
